### ISSUE TITLE
List course dates in chronological order

### ISSUE THREAD

**Issue by christodewit** [kartoza/docker-mezzanine#189] opened 2017-03-28 07:09 UTC
# **Issue**
Course dates are mixed and not displayed in [order](http://kartoza.com/en/shop/product/introduction-to-qgis/).
# **Proposed Solution**
Organize the dates in Chronological order from first to last.

**Comment by gubuntu** [comment] 2017-03-28 07:12
duplicate of #148

**Closed as completed** 2017-07-19 13:14 UTC
